# Product Definition Template

# Product description document defines some of the metadata common to all the datasets belonging to the products. 
# It also describes the measurements that product has and some of the properties of the measurements.

#Product Name
name:

# Product Description
description:

#metadata_type
metadata_type:

# Metadata dictionaary containing metadata common to all the datasets in the product
# Information is stored as a JSON object in dataset_type.metadata attribute, and is used during indexing to auto match datasets to products
metadata:
  platform:
    code:
  instrument:
    name: 
  product_type:
  format:
    name:

# Optional 
# Describes some of the common storage attributes of all the datasets. Definiting this will make a product easier to access and use.
storage:
  # Coordinate reference system common to all the datasets in the product, EPSG code or WKT string.
  crs:
  #resolution of the datasets in the product specified in projection units. Lat/Lon if projection is geographic, x/y elsewise
  resolution:

# List of measurements in this product
# Stored as a JSON object in dataset_type.measurements
measurements:
    # Name of the Measurement
  - name:
    #Units of the measurement
    units:
    # Data type, one of (u)int(8,16,32,64), float32, float64
    dtype:
    # No data value
    nodata:
    # Optional Spectral response of the reflectance measurement
    spectral_definition:
      wavelength : []
      response: []
    # Optional bit flag meanings of the bitset "measurement"
    flags_definition:
      platform:
        bits: []
        description: 
        values: 
      contiguous:
        bits:
        description: 
        values: {}
